- name: set hostname
  template: 
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
  notify: update hostname

- name: set vconsole keymap
  lineinfile: 
    dest: /etc/vconsole.conf 
    create: yes
    regexp: "^KEYMAP="
    line: "KEYMAP=us"

- name: set vconsole font
  lineinfile:
    dest: /etc/vconsole.conf
    create: yes
    regexp: "^FONT="
    line: "FONT=lat2-16"

- name: set available locales
  template: 
    src: locale.gen.j2
    dest: /etc/locale.gen
    owner: root
    group: root
  notify: generate locales

- name: set default locale
  template:
    src: locale.j2
    dest: /etc/locale.conf
    owner: root
    group: root

- name: ensure ext4 module is loaded before updating
  modprobe: 
    name: ext4
    state: present

- name: update system
  pacman:
    upgrade: yes

- include: yaourt.yml

# Run all handlers after finishing the initial configuration
# (so locales and hostname are ready)
- meta: flush_handlers
