# These packages are required for the build to pass correctly
- name: Install required packages
  pacman: name={{ item }} state=present
  with_items:
    - base
    - base-devel
    - zsh
    - grml-zsh-config
    - crda
    - gvim # vim would be enough though
    - syslinux
    - mkinitcpio-nfs-utils
    - ntfs-3g
    - pv # pipe viewer
    - memtest86+

