- name: configure sysctl (swappiness and sysrq)
  copy:
    src: 99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: configure wireless-regdom
  lineinfile:
    dest: /etc/conf.d/wireless-regdom
    regexp: WIRELESS_REGDOM="SK"
    line: WIRELESS_REGDOM="SK"

- name: configure makepkg
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: MAKEFLAGS=
    line: MAKEFLAGS="-j4"

- name: fix boot configuration after changing UUIDs of partitions
  command: grub-mkconfig > /boot/grub/grub.cfg

- name: enable systemd services
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - NetworkManager
    - acpid
    - gpm

- name: disable systemd services
  systemd:
    name: "{{ item }}"
    enabled: no
  with_items:
    - netctl@enp0s3

- name: sddm configuration file
  copy:
    src: sddm.base.conf
    dest: /etc/sddm.base.conf

- name: sddm contest autologin configuration file
  copy:
    src: sddm.contest.conf
    dest: /etc/sddm.contest.conf

- name: sddm configuration file should be absent before creating symlink
  file:
    dest: /etc/sddm.conf
    state: absent

- name: sddm configuration file default symlink
  file:
    src: "./sddm.base.conf"
    dest: /etc/sddm.conf
    state: link

