- name: contest homedir base
  unarchive:
    src: homedirs-base.tar.xz
    dest: /home/contest/
    creates: /home/contest/.mozilla

- name: training homedir base
  unarchive:
    src: homedirs-base.tar.xz
    dest: /home/training/
    creates: /home/training/.mozilla

- name: contest homedir configuration files
  copy:
    src: home/
    dest: /home/contest/

- name: training homedir configuration files
  copy:
    src: home/
    dest: /home/training/

- name: look and feel package setting
  lineinfile:
    regexp: "LookAndFeelPackage"
    line: "LookAndFeelPackage=sk.oi.oilive.{{version}}"
    dest: /home/{{ item }}/.config/kdeglobals
  with_items:
    - training
    - contest

- name: splashrc theme setting
  lineinfile:
    regexp: "Theme"
    line: "Theme=sk.oi.oilive.{{version}}"
    dest: /home/{{ item }}/.config/ksplashrc
  with_items:
    - training
    - contest

- name: kscreenlockerrc theme setting
  lineinfile:
    regexp: "Theme"
    line: "Theme=sk.oi.oilive.{{version}}"
    dest: /home/{{ item }}/.config/kscreenlockerrc
  with_items:
    - training
    - contest

- name: startupconfig theme setting
  lineinfile:
    regexp: "ksplashrc_ksplash_theme"
    line: "ksplashrc_ksplash_theme=sk.oi.oilive.{{version}}"
    dest: /home/{{ item }}/.config/startupconfig
  with_items:
    - training
    - contest

- name: contest homedir permissions
  file:
    path: /home/contest/
    mode: u=rwX,g-rwx,o-rwx
    owner: contest
    group: users
    recurse: yes

- name: training homedir permissions
  file:
    path: /home/training/
    mode: u=rwX,g-rwx,o-rwx
    owner: training
    group: users
    recurse: yes
